project_name               = "tp-terraform-lucas_riyad"
owner                      = "lucas.guillemin@efrei.fr"
environment                = "dev"
my_ip                      = "13.38.32.38/32"
aws_region                 = "eu-west-3"
vpc_cidr                   = "10.0.0.0/16"
public_subnet_cidr         = "10.0.1.0/24"
instance_type              = "t3.micro"
ubuntu_ami_owner           = "099720109477"
ubuntu_ami_filter          = "ami-0adb8ca49015e0901"
random_suffix_length       = 4
enable_dns_hostnames       = true
enable_dns_support         = true
s3_versioning_status       = "Enabled"
s3_encryption_algorithm    = "AES256"
ssh_port                   = 22
http_port                  = 80
https_port                 = 443
allow_all_cidr             = "0.0.0.0/0"
root_volume_size           = 20
root_volume_type           = "gp3"
root_volume_encrypted      = true
sg_web_description         = "Security Group pour le serveur web"
sg_ssh_description         = "SSH depuis ma machine"
sg_http_description        = "HTTP public"
sg_https_description       = "HTTPS public"
sg_egress_description      = "Tout le trafic sortant"

